AWSTemplateFormatVersion: "2010-09-09"
Description: Climate Analysis Tool EMR cluster

Parameters:
  CoreEbsVolumeSize:
    Type: Number
    Default: 32
    Description: Core node EBS volume size in GB
  CoreInstanceCount:
    Type: Number
    Default: 2
    Description: Number of core nodes
  CoreInstanceType:
    Type: String
    Default: m4.large
    Description: Core node instance type
  MasterInstanceType:
    Type: String
    Default: m4.large
    Description: Master node instance type
  ReleaseLabel:
    Type: String
    Default: emr-5.12.1
    Description: EMR release label to install

Mappings:
  RegionSpecific:
    ap-southeast-2:
      KeyPair: home-ap-southeast-2
      MasterSecurityGroup: sg-04c6e263
      SubnetId: subnet-fab3cb8d
    us-east-1:
      KeyPair: home-us-east-1
      MasterSecurityGroup: sg-1ff63b65
      SubnetId: subnet-1a1ace30

Resources:
  Cluster:
    Type: AWS::EMR::Cluster
    Properties:
      Instances:
        AdditionalMasterSecurityGroups:
          - Fn::FindInMap:
              - RegionSpecific
              - Ref: AWS::Region
              - MasterSecurityGroup
        CoreInstanceGroup:
          EbsConfiguration:
            EbsBlockDeviceConfigs:
              - VolumeSpecification:
                  SizeInGB:
                    Ref: CoreEbsVolumeSize
                  VolumeType: gp2
            EbsOptimized: true
          InstanceCount:
            Ref: CoreInstanceCount
          InstanceType:
            Ref: CoreInstanceType
        Ec2KeyName:
          Fn::FindInMap:
            - RegionSpecific
            - Ref: AWS::Region
            - KeyPair
        Ec2SubnetId:
          Fn::FindInMap:
            - RegionSpecific
            - Ref: AWS::Region
            - SubnetId
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType:
            Ref: MasterInstanceType
      JobFlowRole: EMR_EC2_DefaultRole
      LogUri:
        Fn::Sub: s3://aws-logs-${AWS::AccountId}-${AWS::Region}/elasticmapreduce/
      Name: Climate Analysis Tool
      ReleaseLabel:
        Ref: ReleaseLabel
      ServiceRole: EMR_DefaultRole
      Tags:
        - Key: Name
          Value: Climate Analysis Tool
      VisibleToAllUsers: true
  EnableDebuggingStep:
    Type: AWS::EMR::Step
    Properties:
      Name: Enable Hadoop debugging
      ActionOnFailure: CONTINUE
      HadoopJarStep:
        Jar: command-runner.jar
        Args:
          - state-pusher-script
      JobFlowId:
        Ref: Cluster

Outputs:
  ClusterId:
    Description: Cluster ID
    Value:
      Ref: Cluster
  MasterPublicDNS:
    Description: Master node public DNS name
    Value:
      Fn::Sub: ${Cluster.MasterPublicDNS}
